// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todoapp.server.Models;

#nullable disable

namespace todoapp.server.Migrations
{
    [DbContext(typeof(Prn231ProjectContext))]
    [Migration("20251102161834_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("todoapp.server.Models.List", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__List__3214EC0731A512E6");

                    b.HasIndex("UserId");

                    b.ToTable("List", (string)null);
                });

            modelBuilder.Entity("todoapp.server.Models.StickyNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("StickyNote_pk");

                    b.HasIndex("UserId");

                    b.ToTable("StickyNote", (string)null);
                });

            modelBuilder.Entity("todoapp.server.Models.SubTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("SubTask", (string)null);
                });

            modelBuilder.Entity("todoapp.server.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Tags__3214EC0782B50CF2");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("todoapp.server.Models.TagsTask", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("TagsId", "TaskId")
                        .HasName("PK__TagsTask__D3F7FF67372D1309");

                    b.HasIndex("TaskId");

                    b.ToTable("TagsTask", (string)null);
                });

            modelBuilder.Entity("todoapp.server.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int?>("ListId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Task__3214EC07E554C5CF");

                    b.HasIndex("ListId");

                    b.ToTable("Task", (string)null);
                });

            modelBuilder.Entity("todoapp.server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0703D6E2F6");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("todoapp.server.Models.List", b =>
                {
                    b.HasOne("todoapp.server.Models.User", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__List__UserID__45F365D3");

                    b.Navigation("User");
                });

            modelBuilder.Entity("todoapp.server.Models.StickyNote", b =>
                {
                    b.HasOne("todoapp.server.Models.User", "User")
                        .WithMany("StickyNotes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__StickyNot__Accou__46E78A0C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("todoapp.server.Models.SubTask", b =>
                {
                    b.HasOne("todoapp.server.Models.Task", "Task")
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("SubTask_Task_Id_fk");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("todoapp.server.Models.TagsTask", b =>
                {
                    b.HasOne("todoapp.server.Models.Tag", "Tags")
                        .WithMany("TagsTasks")
                        .HasForeignKey("TagsId")
                        .IsRequired()
                        .HasConstraintName("FK__TagsTask__TagsId__440B1D61");

                    b.HasOne("todoapp.server.Models.Task", "Task")
                        .WithMany("TagsTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TagsTask__TaskId__44FF419A");

                    b.Navigation("Tags");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("todoapp.server.Models.Task", b =>
                {
                    b.HasOne("todoapp.server.Models.List", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Task_List_Id_fk");

                    b.Navigation("List");
                });

            modelBuilder.Entity("todoapp.server.Models.List", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("todoapp.server.Models.Tag", b =>
                {
                    b.Navigation("TagsTasks");
                });

            modelBuilder.Entity("todoapp.server.Models.Task", b =>
                {
                    b.Navigation("SubTasks");

                    b.Navigation("TagsTasks");
                });

            modelBuilder.Entity("todoapp.server.Models.User", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("StickyNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
